apiVersion: v1
kind: Service
metadata:
  name: karsajobs-ui
  labels:
    app: karsajobs-ui
    tier: frontend
spec:
  type: NodePort
  selector:
    app: karsajobs-ui
    tier: frontend
  ports:
    - port: 8000
      targetPort: 8000

    