version: 2.1
jobs:
  lint-dockerfile:
    docker:
      - image: hadolint/hadolint:latest-debian
    steps:
      - checkout
      - run:
          name: Lint Dockerfile
          command: hadolint Dockerfile

  build-app-karsajobs-ui:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push image
          command: |
            docker build -t ghcr.io/figoperdana/karsajobs-ui:latest .
            echo "$GHCR_TOKEN" | docker login ghcr.io -u figoperdana --password-stdin
            docker push ghcr.io/figoperdana/karsajobs-ui:latest

workflows:
  version: 2
  build:
    jobs:
      - lint-dockerfile
      - build-app-karsajobs-ui