apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - image: ghcr.io/figoperdana/order-service:latest
          name: order-service
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-release-rabbitmq
                  key: rabbitmq-password
            - name: AMQP_URL
              value: amqp://user:$(RABBITMQ_PASSWORD)@$(MY_RELEASE_RABBITMQ_SERVICE_HOST):5672