apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
  labels:
    app: shipping-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
    spec:
      containers:
        - image: ghcr.io/figoperdana/shipping-service:latest
          name: shipping-service
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-release-rabbitmq
                  key: rabbitmq-password
            - name: AMQP_URL
              value: amqp://user:$(RABBITMQ_PASSWORD)@$(MY_RELEASE_RABBITMQ_SERVICE_HOST):5672